---
title: "Assignment 2 - Research Proposal"
author: "Md Mujahedul Islam" "Johannes Schulz-Knappe"
date: "April 14, 2016"
output: 
  pdf_document:
    toc: true
    number_sections: true
    fig_captions: true
bibliography: 
  - Library.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

This research proposal is the second assignment for the course [MPP-E1180: Introduction to Collaborative Social Science Data Analysis](https://github.com/HertieDataScience/SyllabusAndLectures), taught by [Christopher Gandrud](https://github.com/christophergandrud) at the Hertie School of Governance in spring term 2016. In this proposal, we select our research topic, provide information on its relevance, present current literature, and identify the datasets and methodology that we are going to base our work on.


# The Research Project

On March 13, 2016, Germany's political landscape experienced "a landslide"[@Zeit2016]. At the three state elections in Bade-Württemberg, Rhineland-Palatinate, and Saxony-Anhalt, the young party "Alternative für Deutschland" (Alternative for Germany) received double digit results from scratch, meaning that it has not been present in the state parliaments before. In Baden-Württemberg (BW), the party received 15.1%, in Rhineland-Palatinate (RP) 12.6%, and in Saxony-Anhalt (SA) even 24.3%.(Wikipedia 202-205), becoming the third strongest party in BW and RP, and the second strongest in SA.
Not only does the tremendous success of this new policital player harden the set up of the future governments in the respective states [@Spiegel2016], it is also a clear sign that the party has arrived in mainstream politics in Germany. There is currently a lot of public discussion on the reasons for this success, which is why we consider it to be important to understand in which environments the AfD could gain support.

We want to analyze: 

*"What explains the electoral success of the AfD in the different state constituencies in Baden-Württemberg, Rhineland-Palatinate, and Saxony-Anhalt"*. 

We want to understand which structural factors correlate the vote share and whether the characteristics of AfD voters identified in post-election analyses are reflected in the constituency level data. Furthermore, we want to find out whether the AfD success follows the same patterns as the electoral success of radical right populist parties in the rest of western Europe.

# About the AfD

Having been founded in February 2013 initially as a eurosceptic party, the AfD just missed the entry into the German national parliament at the federal elections in September 2013 by only 125,000 votes [@SchmittBeck2015]. Not a single party in the post-war era was that successful in national elections being only established seven months before[@Niedermayer2014]. 
This emergence is attributed to the Eurocrisis and chancelor Merkels strong state interventionist austerity politcs that opened political potential to the right of the established right parties CDU/CSU and FDP. The AfD recognized that potential and positioned itself initially as an expert knowledge based eurosceptic party. But over the last years, it became a new host for now unrepresented national conservatives as well as right wing populists. The unifying factors for these different groups are the anti-establishment attitude of the AfD and the image of being the political underdog that is "honest" in face of political and medial lies. In this regard, the AfD shares similarities to other European right wing populist parties [@Hausler2015].

The recent refugee crisis that has hit Europe and especially Germany is seen as a major factor that led to new and increased support for the AfD. Chancelor Angela Merkels slogan "Wir schaffen das", expressing optimism with regards to the capability of government and society to deal with the refugee crisis, was only critized by members of the AfD and few from the CDU itself. As long as the refugee crisis persists, it is assumed that the AfD is going to continue to gain more support [@Spiegel2016].

After the March elections, a large debate arose within the CDU/CSU whether the refugee crisis response by chancellor Angela Merkal was responsible for the loss in votes for the CDU. Interestingly, leaders of other parties who supported Merkels "Wir schaffen das" experienced less loss of votes. However, left parties such as "Die Linke" seemed to be especially vulnerable to the emergence of the AfD.[@Spiegel2016] Also, the social democrats (SPD) seem to have lost many voters to the AfD [@Zeit2016].


# Literature review

Early electoral analysis has shown that the AfD was especially successful in mobilizing former non-voters [@Spiegel2016]. It was also very successful amongst labourers and unemployed people. In Saxony-Anhalt, almost one third of this group voted for the AfD. But the analysis also showed that more people with medium education and income voted for the AfD. It is suggested that they are increasingly afraid of change, see the refugee crisis as a culmination of external threat, and are sceptical in the governments capacity to solve it.[@Zeit2016]

In a mixed-methods study focussing on the AfD's history, self-description, positioning in the public discourse, and its supporters, @Berbuir2015 found that the party can be described as a "functional equivalent for a right-wing populist party in a country where right-wing politics are strongly stigmatised" [@Berbuir2015]. For our research this means that the AfD can be located in the tradtion of new radical right wing populist (RRWP) parties in western Europe.

When it comes to the understanding of the rise of RRWP parties, @Ivarsflaten2008 and @Swank2004 offer important insights.
In their large scale study comparing the electoral success of RRWP parties, @Ivarsflaten2008 found that successful RRWP parties almost always used anti-immigration rhethorics in their electoral campaigns. The other two focus areas of RRWP parties - opposing political elitism and complains about the economic development - were not always important for electoral success and seem to be more context specific.
@Swank2004 analyzed the impact of globalization on the electoral success of RRWP parties in national elections in 16 Western European nations between 1981 and 1998. Their core finding was that the generousity of the welfare state was an important factor that mitigated the impact of economic globalizations on the rise of RRWP parties. Besides that, they found that the volume of refugees and asylum seekers, the level of international immigration, the height of  domestic tax burden, previous electoral success of left libertarian parties, and the past voteshare of the RRWP parties all systematically and positively influenced their electoral success. In some occasions, previously declining strength of established right-wing parties was another factor that explained RRWP party success. Interestingly, slow economic growth and the rate of people employed in manufacturing jobs did not have a significant impact [@Swank2004, 230].

# Hypotheses

Based on the insights of previous research on the success of RRWP parties in western Europe and the findings of post-election analysis, we propose the following hypotheses for the three state elections.

Socio-demographic hypotheses

> *H1a*: The average level of education in a constituency has a negative impact on the electoral success of the AfD.

> *H1b*: The share of men in a constituency has a positive impact on the electoral success of the AfD.

> *H1c*: The unemployment rate in a constituency has a positive impact on the electoral success of the AfD.


Foreign exposure hypotheses

> *H2a*: The volume of refugees and asylum seekers in a constituency has a positive impact on the electoral success of the AfD.

> *H2b*: The rate of foreign residents in a constituency has a positive impact on the electoral success of the AfD.

Economic hypothesis

> *H3*: The height of local taxes has a positive impact on the electoral success of the AfD.

Political hypotheses

> *H4a*: The rate of non-voters in previous state elections in a constituency has a positive impact on the electoral success of the AfD.

> *H4b*: The vote share of left libertarian parties in previous state elections in a constituency has a positive impact on the electoral success of the AfD.

> *H4c*: Declining voteshare of established right wing parties in previous state elections in a constituency has a positive impact on the electoral success of the AfD.


# Data sources and Methodology

We acess the electoral data via the State Offices for Statistic in Baden-Württemberg [@BWStateOffice], Rhineland-Palatinate [@RPStateOffice], and Saxony-Anhalt [@SAStateOffice]. We will use the datasets on the March 2016 and the previous two elections in order to retrieve the secondary vote share of the AfD as our dependent variable, and the previous vote shares of right and left wing parties for hypotheses H4b and H4c. The rate of previous non-voters is also retreived from these datasets.
The Federal Returning Officer [@Bwldata] offers data on constituency level containing information on the unemployment rate, the level of education, and business tax (which we will use as a proxy for local taxation).
The Federal Statistical Office DESTATIS [@DESTATIS] provides data on gender and the number of refugees in the constituencies. This data is available on county level, which is why will disaggregate the data according to the population size in each constituency.

After merging the data, we will first analyse descriptive statistics in the form of maps, graphs, and distributions in order to provide a basic overview of the trends in the data. We then will perform OLS estimations for different linear models, testing our aforementioned hypotheses.

# References